import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "./components/side-bar";
import TabBar from "./components/tab-bar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ position: "relative", zIndex: 1 }}
      >
        <SideBar>{children}</SideBar>
        <TabBar />
      </body>
    </html>
  );
}
